db:
  image: mysql:latest
  ports:
    - "3306:3306"
  volumes:
    - ./var/mysql:/var/lib/mysql
  environment:
    - MYSQL_DATABASE=db
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=1234
    - MYSQL_ROOT_PASSWORD=1234
# web:
#   image: tutum/apache-php
#   ports:
#     - "80:80"
#     - "443:443"
#   links:
#     - db
#   volumes:
#     - ./www/public:/app